- name: Install gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    executable: "{{ rbenv_directory }}/shims/gem"
  with_items:
    - { name: ocsprf, version: 0.0.2 }

- name: Set OCSP Response fetcher
  block:
    - name: Initial fetch
      shell:
        cmd: "{{ ocsp_response_fetcher_job }}"
        creates:
          - "{{ ocsp_response_fetcher_cache_file }}"
          - "{{ ocsp_response_fetcher_cache_file }}.tmp"
      ignore_errors: True
    - name: Set crontab
      cron:
        name: 'ocsp_response_fetcher'
        hour: '*/1'
        minute: '0'
        job: "sleep $(($RANDOM % 120)); {{ ocsp_response_fetcher_job }}"
        cron_file: ocsp_response_fetcher
        user: root
  vars:
    ocsp_response_fetcher_job: "{{ rbenv_directory }}/shims/ocsprf
     /etc/letsencrypt/live/{{ domain }}/cert.pem
     --issuer /etc/letsencrypt/live/{{ domain }}/chain.pem
     --verbose --output {{ ocsp_response_fetcher_cache_file }}"
