- name: Install crontabs
  ansible.builtin.yum:
    name: crontabs

- name: Install gems
  community.general.gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: false
    executable: "{{ rbenv_directory }}/shims/gem"
  with_items:
    - { name: ocsprf, version: 0.0.2 }

- name: Set OCSP Response fetcher
  block:
    - name: Initial fetch
      ansible.builtin.command:
        cmd: "{{ ocsp_response_fetcher_job }}"
        creates:
          - "{{ ocsp_response_fetcher_cache_file }}"
      ignore_errors: true
    - name: Set crontab
      ansible.builtin.cron:
        name: 'ocsp_response_fetcher'
        weekday: '6'
        hour: '22'
        minute: '0'
        job: "{{ ocsp_response_fetcher_job }}"
        cron_file: ocsp_response_fetcher
        user: root
  vars:
    ocsp_response_fetcher_job: "{{ rbenv_directory }}/shims/ocsprf
     /etc/letsencrypt/live/{{ domain }}/cert.pem
     --issuer /etc/letsencrypt/live/{{ domain }}/chain.pem
     --verbose --output {{ ocsp_response_fetcher_cache_file }}"
