- name: Install "{{ packages }}"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - git-core
      - gcc
      - make
      - readline-devel
      - bzip2
      - perl-core
      - zlib-devel

- name: Check whether openssl is installed
  shell: bash -lc "openssl version | grep {{ openssl_version }}"
  ignore_errors: True
  register: openssl_version_check

- name: Download openssl
  get_url:
    url: "https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz"
    dest: "{{ openssl_directory_prefix }}/src/openssl-{{ openssl_version }}.tar.gz"
    checksum: "sha256:{{ openssl_file_sha256 }}"
  when: openssl_version_check.rc != 0

- name: Unarchive openssl
  unarchive:
    src: "{{ openssl_directory_prefix }}/src/openssl-{{ openssl_version }}.tar.gz"
    dest: "{{ openssl_directory_prefix }}/src"
    remote_src: yes
  when: openssl_version_check.rc != 0

- name: Install openssl
  shell: |
    ./config --prefix={{ openssl_directory }} shared zlib
    make depend
    make
    make install
  args:
    chdir: "{{ openssl_directory_prefix }}/src/openssl-{{ openssl_version }}"
  when: openssl_version_check.rc != 0

- name: Template openssl.sh
  template:
    src: openssl.sh.j2
    dest: /etc/profile.d/openssl.sh
    owner: root
    group: root

- name: Template openssl.conf
  template:
    src: openssl.conf.j2
    dest: /etc/ld.so.conf.d/openssl.conf
    owner: root
    group: root

- name: Configure openssl library path
  shell: ldconfig

- name: Download rbenv
  git:
    repo: https://github.com/sstephenson/rbenv.git
    dest: "{{ rbenv_directory }}"

- name: Download ruby-build
  git:
    repo: https://github.com/sstephenson/ruby-build.git
    dest: "{{ rbenv_directory }}/plugins/ruby-build"

- name: Template rbenv.sh
  template:
    src: rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: root
    group: root

- name: Check ruby version and openssl version installed with ruby
  shell: bash -lc "ruby --version | grep {{ ruby_version }} && ruby -ropenssl -e'puts OpenSSL::OPENSSL_VERSION' | grep {{ openssl_version }}"
  ignore_errors: True
  register: ruby_openssl_version_check

- name: Install ruby
  shell: CONFIGURE_OPTS="--with-openssl-dir={{ openssl_directory }}" bash -lc "rbenv install --force {{ ruby_version }}"
  when: ruby_openssl_version_check.rc != 0

- name: Globalize ruby
  shell: bash -lc "rbenv global {{ ruby_version }}"

- name: Install gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    executable: "{{ rbenv_directory }}/shims/gem"
  with_items:
    - { name: http_parser.rb, version: 0.6.0 }
    - { name: logger, version: 1.4.2 }
    - { name: openssl, version: 2.1.2 }
    - { name: timeout, version: 0.0.1 }
    - { name: tttls1.3, version: 0.2.14 }

- name: Make directory
  file:
    path: "{{ openssl_directory }}/ssl"
    state: directory
    recurse: true
    owner: root
    mode: 0755

- name: Install cacert.pem
  get_url:
    url: https://curl.haxx.se/ca/cacert.pem
    dest: "{{ openssl_directory }}/ssl/cert.pem"
    force: yes
