- name: Make directory
  ansible.builtin.file:
    path: "{{ https_server_directory }}"
    state: directory
    recurse: true
    owner: tttls1.3_https
    group: wheel
    mode: 0755

- name: Template server.rb
  ansible.builtin.template:
    src: server.rb.j2
    dest: "{{ https_server_directory }}/server.rb"
    owner: tttls1.3_https
    group: wheel
    mode: 0644

- name: Copy index.html
  ansible.builtin.copy:
    src: index.html
    dest: "{{ https_server_directory }}/index.html"
    owner: tttls1.3_https
    group: wheel
    mode: 0644

- name: Template tttls1.3_https.service
  ansible.builtin.template:
    src: tttls1.3_https.service.j2
    dest: /etc/systemd/system/tttls1.3_https.service
    owner: root
    group: root
    mode: 0600

- name: Enable tttls1.3_https.service
  ansible.builtin.systemd:
    name: tttls1.3_https.service
    state: restarted
    daemon_reload: true
    enabled: true
