- name: Make directory
  file:
    path: "{{ https_server_directory }}"
    state: directory
    recurse: true
    owner: tttls1.3_https
    group: wheel
    mode: 0755

- name: Template server.rb
  template:
    src: server.rb.j2
    dest: "{{ https_server_directory }}/server.rb"
    owner: tttls1.3_https
    group: wheel
    mode: 0644

- name: Template tttls1.3_https.service
  template:
    src: tttls1.3_https.service.j2
    dest: /etc/systemd/system/tttls1.3_https.service
    owner: root
    group: root
    mode: 0600

- name: Enable tttls1.3_https.service
  systemd:
    name: tttls1.3_https.service
    state: restarted
    daemon_reload: yes
    enabled: yes
