https_rbenv_directory:
  /opt/rbenv
https_rbenv_version:
  v1.3.0
https_ruby_build_version:
  v20240917
https_ruby_version:
  3.1.6
https_gems:
  - name:
      http_parser.rb
    version:
      0.8.0
  - name:
      logger
    version:
      1.6.1
  - name:
      openssl
    version:
      3.2.0
  - name:
      timeout
    version:
      0.4.1
  - name:
      tttls1.3
    version:
      0.3.3
  - name:
      webrick
    version:
      1.8.2
https_server_directory:
  /opt/tttls1.3_https
https_openssl_version:
  3.3.2
https_openssl_file_sha256:
  2e8a40b01979afe8be0bbfb3de5dc1c6709fedb46d6c89c10da114ab5fc3d281
https_openssl_directory_prefix:
  /usr/local/
https_openssl_directory:
  "{{ https_openssl_directory_prefix }}/openssl-{{ https_openssl_version }}"
