- name: Template sshrc
  ansible.builtin.template:
    src: sshrc.j2
    dest: /etc/ssh/sshrc
    owner: root
    group: root
    mode: "0755"

- name: Install "{{ packages }}"
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - iproute
      - crontabs

- name: Make directory
  ansible.builtin.file:
    path: /opt/paranoids
    state: directory
    recurse: true
    owner: root
    group: root
    mode: "0755"

- name: Template paranoids_ss.sh
  ansible.builtin.template:
    src: paranoids_ss.sh.j2
    dest: /opt/paranoids/paranoids_ss.sh
    owner: root
    group: root
    mode: "0755"

- name: Set crontab to monitor dest-ports
  ansible.builtin.cron:
    name: 'monitoring dest-ports'
    minute: '*/1'
    job: /bin/bash /opt/paranoids/paranoids_ss.sh
    cron_file: paranoids_ss
    user: root
