- name: Install openssl
  yum:
    name: openssl

- name: Make directory
  file:
    path: "/etc/letsencrypt/live/{{ domain }}/"
    state: directory
    recurse: true
    owner: root
    group: root
    mode: 0644

- name: Copy private certificate
  copy:
    src: "{{ item }}"
    dest: "/etc/letsencrypt/live/{{ domain }}/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - cert.pem
    - chain.pem
    - privkey.pem
