- name: Install certbot
  yum:
    name: certbot

- name: Check existence of a certificate
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
  register: fullchain

- name: Check existence of a private-key
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
  register: privkey

- name: Issue a certificate with ACME
  command:
    cmd: bash -lc "certbot certonly
      --standalone
      --domain {{ domain }}
      --domain www.{{ domain }}
      --email {{ certbot_email }}
      --agree-tos
      --no-eff-email
      --pre-hook 'systemctl stop tttls1.3_https'
      --preferred-chain 'ISRG Root X1'"
  when: not (fullchain.stat.exists and privkey.stat.exists)

- name: Renew a certificate
  command:
    cmd: bash -lc 'certbot renew
      --pre-hook "systemctl stop tttls1.3_https"
      --max-log-backups 10
      --preferred-chain "ISRG Root X1"'
  when: fullchain.stat.exists and privkey.stat.exists

- name: Set crontab of certbot
  cron:
    name: 'certbot renew'
    weekday: '0'
    hour: '2'
    minute: '0'
    job: '/usr/bin/certbot renew
     --pre-hook "/usr/bin/systemctl stop tttls1.3_https"
     --post-hook "/usr/bin/systemctl start tttls1.3_https"
     --max-log-backups 10
     --preferred-chain "ISRG Root X1"'
    cron_file: certbot_renew
    user: root
