- name: Install certbot
  yum:
    name: certbot

- name: Check existence of a certificate
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/fullchain.pem"
  register: fullchain

- name: Check existence of a private-key
  stat:
    path: "/etc/letsencrypt/live/{{ domain }}/privkey.pem"
  register: privkey

- name: Issue a certificate with ACME
  shell: bash -lc "certbot certonly --standalone --domain {{ domain }} --email {{ certbot_email }} --agree-tos --no-eff-email"
  when: fullchain.stat.exists == False or privkey.stat.exists == False

- name: Renew a certificate
  shell: bash -lc "certbot renew"
  when: not (fullchain.stat.exists == False or privkey.stat.exists == False)

- name: Set crontab of certbot
  cron:
    name: 'certbot renew'
    weekday: '0'
    hour: '2'
    minute: '0'
    job: 'certbot renew'
    cron_file: certbot_renew
    user: root
