name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip --version
          pip install -r requirements.txt
      - name: Run lint
        run: |
          ansible --version
          ansible-lint --version
          ansible-playbook -i playbook/dev playbook/{private_certificate,https}.yml --syntax-check
          ansible-playbook -i playbook/prod playbook/{certbot,https,sshd_config}.yml --syntax-check
          find playbook/roles -type f -name '*.yml' | grep -v playbook/roles/paranoids/vars/main.yml | xargs -L1 -I{} ansible-lint {}
