name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies
        run: |
          uv venv
          uv python install
          uv pip sync requirements.txt

      - uses: actions/checkout@v3

      - name: Run lint
        run: |
          uv run ansible --version
          uv run ansible-lint --version
          uv run ansible-playbook -i playbook/dev playbook/{private_certificate,https}.yml --syntax-check
          uv run ansible-playbook -i playbook/prod playbook/{certbot,https,sshd_config}.yml --syntax-check
          find playbook/roles -type f -name '*.yml' | grep -v playbook/roles/paranoids/vars/main.yml | xargs -L1 -I{} uv run ansible-lint {}
