name: workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - name: Set up Python
        uses: actions/setup-python@v1
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          pip3 --version
          pip3 install -r requirements.txt
      - name: Run lint
        run: |
          ansible --version
          ansible-lint --version
          ansible-playbook -i playbook/dev playbook/{private_certificate,https}.yml --syntax-check
          ansible-playbook -i playbook/prod playbook/{certbot,https,sshd_config}.yml --syntax-check
          ansible-lint playbook/roles/*/tasks/**.yml
